import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.guru99.com/test/newtours/register.php');
  await page.locator('input[name="firstName"]').click();
  await page.locator('input[name="firstName"]').fill('shrikant');
  await page.locator('input[name="lastName"]').click();
  await page.locator('input[name="lastName"]').fill('Khemkar');
  await page.locator('input[name="phone"]').click();
  await page.locator('input[name="phone"]').fill('85986589');
  await page.locator('#userName').click();
  await page.locator('#userName').fill('shri@yopmail.com');
  await expect(page.locator('#userName')).toHaveValue('shri@yopmail.com');
  await expect(page.locator('body')).toContainText('Contact Information');
  await page.locator('input[name="address1"]').click();
  await page.locator('input[name="address1"]').fill('Pune');
  await page.locator('input[name="address1"]').press('Tab');
  await page.locator('input[name="city"]').fill('Pune');
  await page.locator('input[name="city"]').press('Tab');
  await page.locator('input[name="state"]').fill('MH');
  await page.locator('input[name="state"]').press('Tab');
  await page.locator('input[name="postalCode"]').fill('145287');
  await page.getByRole('combobox').selectOption('INDIA');
  await expect(page.getByText('Country:')).toBeVisible();
  await expect(page.locator('body')).toContainText('City');
  await expect(page.getByRole('combobox')).toHaveValue('INDIA');
  await page.locator('#email').click();
  await page.locator('#email').fill('shrikant');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('shri@123');
  await page.locator('input[name="confirmPassword"]').click();
  await page.locator('input[name="confirmPassword"]').fill('shri@123');
  await expect(page.getByRole('button', { name: 'Submit' })).toBeVisible();
  await expect(page.locator('body')).toContainText('User Name');
  await expect(page.locator('#email')).toHaveValue('shrikant');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('body')).toContainText('Note: Your user name is shrikant.');
  await expect(page.getByText('Dear shrikant Khemkar,')).toBeVisible();
});